[env]
#For working with older terminals e.g RHEL7
TERM = "xterm-256color"

# For opening new shell in the current PWD on i3
# [keyboard]
# bindings = [
#    { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
# ]

[window]
opacity = 0.8
blur = true
decorations = "buttonless"

option_as_alt = "Both"

[window.padding]
x = 25
y = 20

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 17
