[env]
#For working with older terminals e.g RHEL7
TERM = "xterm-256color"

[keyboard]
bindings = [{ key = "Return", mods = "Shift", chars = "\u001b\r" }]

# For opening new shell in the current PWD on i3
# bindings = [
#    { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
# ]

[window]
#opacity = 0.8
#blur = false
decorations = "buttonless"

option_as_alt = "Both"

[window.padding]
x = 25
y = 20

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 16
